### ISSUE TITLE
pyzmq=23.0.0 changes names of constants

### ISSUE THREAD

**Issue by dihm** [chrisjbillington/zprocess#17]
Just hit this in an RTD [build](https://readthedocs.org/projects/labscript-devices/builds/17070776/). Newest pyzmq moved all constant definitions to python enums that are introspected from zmq.h. This changes the names of certain constants. The present example is `zmq.EVENT_HANDSHAKE_SUCCEEDED` is now `zmq.HANDSHAKE_SUCCEEDED`. List of new constant names can be found in this [file](https://github.com/zeromq/pyzmq/blob/main/zmq/constants.py).

I imagine this has the potential to break a fair number of things beyond what I've noticed.

**Comment by chrisjbillington** [comment]
Thanks for the report. I suspect this is unintentional and will report a bug to pyzmq - they'll likely want to include constants under the old names at least for a time for backwards compatibility.

Changing the code here would be easy enough, but we would need to then bump the required pyzmq version or write the code to work with either. Bumping the required pyzmq will prevent new zprocess releases being installable with anaconda since it will take time for the new pyzmq to hit their repos, and writing little checks to access constants is annoying.

**Comment by chrisjbillington** [comment]
Reported here: https://github.com/zeromq/pyzmq/issues/1710

**Comment by dihm** [comment]
Huzzah! As usual, I figured you would know the best way to fix this quickly. Glad it didn't require any pinning of modules or hotfixes you this end.
