### ISSUE TITLE
Cannot bind `'tcp://0.0.0.0:*'` to a `SecureSocket` with pyzmq>=26.0.0

### ISSUE THREAD

**Issue by dihm** [chrisjbillington/zprocess#22]
This issue has been cropping up in labscript for a little while now, but finally got around to tracking down the exact version and a minimum reproducible example.

```python
import zmq
from zprocess.security import generate_shared_secret, SecureContext

print('pyzmq==',zmq.pyzmq_version_info())
print('zmq==',zmq.zmq_version_info())


if __name__ == '__main__':

    # first test a plain Context/Socket
    server_ctx = zmq.Context.instance()
    client_ctx = zmq.Context.instance()

    server = server_ctx.socket(zmq.PULL)
    client = client_ctx.socket(zmq.PUSH)

    addr = "tcp://0.0.0.0"
    #addr = "tcp://127.0.0.1"
    port = server.bind_to_random_port(addr)
    client.connect(f'tcp://127.0.0.1:{port:d}')
    client.send(b'hello')
    assert server.recv() == b'hello'  # always succeeds

    # tidy
    del client, server, client_ctx, server_ctx

    #re-run with SecureContext/Socket
    shared_secret = generate_shared_secret()
    other_secret = generate_shared_secret()

    server_ctx = SecureContext.instance(shared_secret=shared_secret)
    client_ctx = SecureContext.instance(shared_secret=shared_secret)

    server = server_ctx.socket(zmq.PULL)
    client = client_ctx.socket(zmq.PUSH)

    addr = "tcp://0.0.0.0"
    #addr = "tcp://127.0.0.1"  # using the explicit local address allows the following function to run without error
    port = server.bind_to_random_port(addr)  # throws error with pyzmq>=26
    client.connect(f'tcp://127.0.0.1:{port:d}')
    client.send(b'hello')
    assert server.recv() == b'hello'
```

The produced error is
```shell
pyzmq== (26, 2, 0)
zmq== (4, 3, 5)
Traceback (most recent call last):
  File "C:\Users\David\src\scripts\zprocess_checker.py", line 38, in <module>
    port = server.bind_to_random_port(addr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Miniconda3\envs\labscript\Lib\site-packages\zmq\sugar\socket.py", line 499, in bind_to_random_port
    self.bind(f"{addr}:*")
  File "C:\Miniconda3\envs\labscript\Lib\site-packages\zprocess\security.py", line 217, in bind
    return self._bind_or_connect(addr, bind=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Miniconda3\envs\labscript\Lib\site-packages\zprocess\security.py", line 204, in _bind_or_connect
    result = method(self, addr)
             ^^^^^^^^^^^^^^^^^^
  File "C:\Miniconda3\envs\labscript\Lib\site-packages\zmq\sugar\socket.py", line 311, in bind
    super().bind(addr)
  File "_zmq.py", line 917, in zmq.backend.cython._zmq.Socket.bind
  File "_zmq.py", line 179, in zmq.backend.cython._zmq._check_rc
zmq.error.ZMQError: No such device (addr='tcp://0.0.0.0:*')
```

@chrisjbillington If something obvious jumps out to you for what the source is, let me know. Otherwise I'll probably circle back to debugging this in a few days.

All testing is done using pip installed pyzmq since conda's zeromq==4.3.5 is still borked.

**Comment by chrisjbillington** [comment]
It's about ipv6. Whilst there may be more to it, it seems `0.0.0.0` may no longer be a valid way to specify "all interfaces", on Windows at least, when ipv6 is enabled. zprocesss `SecureSocket`s have ipv6 enabled by default (`self.ipv6 = True` in `SecureSocket.__init__`), which is why it affects them and not plain `zmq.Socket`s.

If you disable ipv6:

```python
    server.ipv6 = False
```

before binding the socket, then the error doesn't occur. And on Linux it seemingly doesn't occur regardless.

These seem to be the options for binding to all interfaces:

```
    addr = "tcp://[::]" # Works only if server.ipv6 is True
    addr = "tcp://0.0.0.0" # On Windows, only works if server.ipv6 is False, always works on Linux
    addr = "tcp://*" # Always works
```

Even if the client has ipv6 disabled, it still seems to be able to connect to the server bound to `[::]`, even though that's shorthand for the ipv6 equivalent of `0.0.0.0`, i.e. `0000:0000:0000:0000:0000:0000:0000:0000` (which you can abbreviate as `::` and which zeromq requires you to wrap in square brackets to be able to distinguish the address and port from each other).

Seems like to be sure, people should always use `tcp://*`, is there any known downside to that?

**Comment by dihm** [comment]
I can't seem to find any downside to `tcp://*`. Of course, I can barely find documentation that says `tcp://0.0.0.0` ever worked.

In any case, quick tests in labscript seem to indicate `tcp://*` works OK on older versions of pyzmq as well as >=26. I'll call this resolved now and fix in labscript_utils.
